language: node_js
node_js: "8"

install:
        - cd frontend
        - npm install
        - cd ..
        - cd backend
        - npm install
        - mv config.template.json config.json

script:
        - make test
