language: node_js
node_js: "8"

install:
        - cd frontend
        - npm install
        - cd ..
        - cd backend
        - npm install
        - mv config.template.json config.json

script:
        - chmod -R +x tests/e2e 
        - ./tests/e2e/smoke-test.sh
        - node ./tests/e2e/test-redirect.js
