[build]
  publish = "dist/"
  command = "cd frontend; make deploy"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/VdCWxpQ"

[[redirects]]
  from = "/reddit"
  to = "https://reddit.com/r/rocketwatch"

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/rocket_watch"
  
[[redirects]]
  from = "/youtube"
  to = "https://www.youtube.com/channel/UCpY48ts_nCvlBRAVlbJePgg" 
