[build]
  base = "/"
  publish = "dist/"
  command = "make deploy"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/cExSaKZ"

[[redirects]]
  from = "/reddit"
  to = "https://reddit.com/r/rocketwatch"

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/rocket_watch"
  
[[redirects]]
  from = "/youtube"
  to = "https://www.youtube.com/channel/UCpY48ts_nCvlBRAVlbJePgg" 
  
[[redirects]]
  from = "https://rocketwatch.yasiu.pl"
  to = "https://rocket.watch"
  status = 301

[[redirects]]
  from = "https://spacex.yasiu.pl"
  to = "https://rocket.watch/#agency=121"
  status = 301
  
[[redirects]]
  from = "https://ula.yasiu.pl"
  to = "https://rocket.watch/#agency=124"
  status = 301
