env:
  commonjs: true
  es6: true
  node: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-template-curly-in-string:
    - error
  no-var:
    - error
  brace-style:
    - error
    - allman
  comma-dangle:
    - error
    - always-multiline
  func-style:
    - error
    - declaration
    - allowArrowFunctions:
        true
  no-param-reassign:
    - error
